// Turns dist/ into a plain JS module, so the packaged executable carries the
// interface in memory without relying on any runtime-specific asset API.
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { extname, join, relative, sep } from 'node:path'

const DIST = 'dist'
const OUT = 'build/embedded-assets.js'

// A local `vite build` copies public/ as is, real exports and backups
// included: they must never end up inside an executable that gets published.
const DATA_FILE = /\.(csv|pdf|xlsx?|ods)$|portefeuille-sauvegarde[^/]*\.json$/i

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.json': 'application/json',
  '.woff2': 'font/woff2',
  '.wasm': 'application/wasm',
  '.txt': 'text/plain; charset=utf-8',
}

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name)
    return statSync(path).isDirectory() ? walk(path) : [path]
  })
}

const assets = {}
const excluded = []
for (const file of walk(DIST)) {
  const urlPath = '/' + relative(DIST, file).split(sep).join('/')
  if (DATA_FILE.test(file)) {
    excluded.push(urlPath)
    continue
  }
  const type = TYPES[extname(file).toLowerCase()]
  if (!type) throw new Error(`Type de fichier non prévu dans dist/ : ${urlPath}`)
  assets[urlPath] = { type, data: readFileSync(file).toString('base64') }
}

if (!assets['/index.html']) {
  throw new Error('dist/index.html absent : lancer `vite build` avant ce script.')
}

mkdirSync('build', { recursive: true })
writeFileSync(
  OUT,
  `// Generated by scripts/embed-dist.mjs. Do not edit.\nexport default ${JSON.stringify(assets)}\n`
)

console.log(`${Object.keys(assets).length} fichiers embarqués dans ${OUT}.`)
if (excluded.length) {
  console.warn(`Exclus car fichiers de données : ${excluded.join(', ')}`)
}
